apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: golang-web
  name: golang-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: golang-web
  strategy: {}
  template:
    metadata:
      labels:
        name: golang-web
    spec:
      containers:
      - image: anguda/golang:jaeger
        imagePullPolicy: ""
        name: golang-web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: golang-web
  name: golang-web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
    nodePort: 32001
  selector:
    name: golang-web
  type: NodePort
