apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db
  strategy: {}
  template:
    metadata:
      labels:
        name: db
    spec:
      containers:
      - image: anguda/mysql
        imagePullPolicy: ""
        name: db
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: db
  name: db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    name: db
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  strategy: {}
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - image: anguda/python-flask-app:web-jaeger
        imagePullPolicy: ""
        name: app
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: app
  name: app
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 32001
  selector:
    name: app
  type: NodePort
status:
  loadBalancer: {}
