version: "2"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment: 
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"  
      - "9411:9411"
  app:
    build: ./app
    environment:
      - JAEGER_AGENT_HOST=jaeger
    links:
      - db
      - jaeger
    ports:
      - "5000:5000"

  db:
    build: ./db
    ports:
      - "3306:3306"
